name: 'Setup Node.js'
description: 'Setup Node and install dependencies using cache'
inputs:
  node-version:
    description: Set a specific node version instead of the default from `.node-version` file.
    required: false
  save-cache:
    description: 'Save cache when needed'
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:
    - name: ⚙️ Calculate `CACHE_KEY`
      shell: bash
      run: |
        if [[ -z '${{ inputs.node-version }}' ]]; then
          node_major=$(grep -E -o '^[0-9]+' .node-version)
        else
          node_major=$(echo '${{ inputs.node-version }}' | grep -E -o '^[0-9]+')
        fi
        echo "CACHE_KEY=node_modules-${{ runner.os }}-v${node_major}-${{
          hashFiles('.node-version', 'pnpm-lock.yaml')
        }}" >> "$GITHUB_ENV"

    - name: ♻️ Restore `node_modules`
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: node-modules-restore
      with:
        path: node_modules
        key: ${{ env.CACHE_KEY }}
        enableCrossOsArchive: true

    - name: Calculate `CACHE_HIT`
      shell: bash
      run: |
        echo 'CACHE_HIT=${{
          (steps.node-modules-restore.outputs.cache-hit == 'true') && 'true' || ''
        }}' >> "$GITHUB_ENV"

    - name: ⚙️ Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        standalone: true

    - name: ⚙️ Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        node-version: ${{ inputs.node-version }}
        cache: ${{ env.CACHE_HIT != 'true' && 'pnpm' || '' }}

    - name: 📥 Install dependencies
      if: env.CACHE_HIT != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        # Other environment variables
        HUSKY: '0' # By default do not run HUSKY install

    - name: ♻️ Write `node_modules` cache
      if: inputs.save-cache == 'true' && env.CACHE_HIT != 'true'
      uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: node_modules
        key: ${{ env.CACHE_KEY }}
        enableCrossOsArchive: true
