notifications:
  email: false

language: node_js

node_js:
- "8.11.1"

sudo: false

install:
- npm install

cache:
  directories:
    - ".cache"
    - ".eslintcache"
    - "node_modules"

script:
  - npm run lint
  - npm run jest --maxWorkers=4

after_success:
  - npm run codecov
