export function compare(version: string, other: string): number;
export function rcompare(version: string, other: string): number;
export function gt(version: string, other: string): boolean;
export function eq(version: string, other: string): boolean;
export function lt(version: string, other: string): boolean;
export function ge(version: string, other: string): boolean;
export function nq(version: string, other: string): boolean;
export function le(version: string, other: string): boolean;
export function arbitrary(version: string, other: string): boolean;